config/routes.rb
Rails.application.routes.draw do
  # Custom pathnames
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register", :edit => "settings" }, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  # Default to cards index
  root to: "home#landing"

  #general pages
  get '/contact_careers' => 'home#contact_careers', as: :contact_careers
  get '/landing' => 'home#landing', as: :landing

  # Real Pages
  get '/cards/index' => 'cards#index', as: :cards_index
  get '/cards/edit/:id' => 'cards#edit', as: :cards_edit
  post '/cards/edit/:id' => 'cards#detail', as: :cards_edit_post_url
  get '/cards/new' => 'cards#new', as: :cards_new_url
  post '/cards/new' => 'cards#newform', as: :cards_post_url
  get '/cards/detail/:id' => 'cards#detail', as: :cards_detail_url
  post '/cards/detail/:id' => 'cards#detail', as: :cards_detail_post_url
  get '/cards/validate/:id' => 'cards#request_validation', as: :cards_validation_get_url
  get '/cards/cancelvalidation/:id' => 'cards#cancelvalidation', as: :cards_validation_cancel_url
  get '/cards/delete/:id' => 'cards#deletecard', as: :cards_delete_url
  get '/cards/undelete/:id' => 'cards#undeletecard', as: :cards_undelete_url
  get '/cards/graveyard' => 'cards#graveyard', as: :cards_graveyard_url

  # experts
  get '/experts' => 'home#showexperts', as: :experts_list_url

  # Vendor/Shopkeeper functionality
  get '/vendor' => 'cardverify#menu', as: :cardverify_menu
  get '/vendor/verify' => 'cardverify#index', as: :cardverify_index
  get '/vendor/reject/:id' => 'cardverify#rejectcard', as: :cardverify_reject
  get '/vendor/accept/:id' => 'cardverify#acceptcard', as: :cardverify_accept
  # Expert user functionality
  get '/expert' => 'cardverify#menu', as: :cardverify_menu_expert

  # Transfer functionality
  post '/cards/transfer' => 'transfer#outbound', as: :cardtransfer_outbound
  get '/cards/transfer/reject/:id' => 'transfer#rejecttransfer', as: :cardtransfer_reject
  get '/cards/transfer/accept/:id' => 'transfer#acceptransfer', as: :cardtransfer_accept
  get '/cards/transfer/incoming' => 'transfer#inbound', as: :cardtransfer_inbound

  # Admin page
  get '/admin' => 'adminpage#index', as: :adminpage_index
  get '/admin/generateinvite' => 'adminpage#generateinvite', as: :adminpage_generateinvite
  get '/admin/users' => 'adminpage#userlist', as: :adminpage_userlist
  get '/admin/transfers' => 'adminpage#transferlist', as: :adminpage_transferlist
  get '/admin/usercards/:id' => 'adminpage#usercards', as: :adminpage_usercards
  get '/admin/graveyard' => 'adminpage#graveyard', as: :adminpage_graveyard
  get '/admin/permadelete/:id' => 'cards#permadeletecard', as: :adminpage_permadelete

  # Fake pages
  get '/cards/transfer' => 'cards/transfer', as: :cards_transfer
  get '/cards/transferred' => 'cards/transferred', as: :cards_transferred
  get '/swhome' => 'home#index'
  match '/old/login' => 'login#login', :via => [:post]
  get '/old/sign_up' => 'login#logup', as: :logup
end

app/controllers/cardverify_controller.rb
class CardverifyController < ApplicationController
  before_action :authenticate_user!

  def index
		if current_user.accounttype == "vendor" or current_user.accounttype == "admin" or current_user.accounttype == "expert" then
      @cardlist = []
      if params[:cardverify] != nil then
        if params[:cardverify][:email] != nil then
          check_cards = Validationqueue.where(:requestor_email_address => params[:cardverify][:email])
          if check_cards.count > 0 then
            check_cards.each {|pc|
              rc = Card.find(pc.card_id)
              if rc.transfer_status == 0 then
                @cardlist << {:cardname => rc.cardname, :_id => rc._id}
              end
            }
          end
        end
      end
      render :template => "cardverify/index"
		else
			# Access denied
			redirect_to "/"
		end
	end

  def menu
    if (current_user.accounttype == "vendor") or (current_user.accounttype == "expert") then
      render :template => "cardverify/menu"
    else
      redirect_to "/"
    end
  end

  def rejectcard
    if (current_user.accounttype == "vendor" and current_user.identity_verified == 1) or (current_user.accounttype == "expert") or (current_user.accounttype == "admin") then
      self.reject_or_approve("reject", params[:id])
      self.redirection
    else
      redirect_to "/"
    end
  end

  def acceptcard
    if (current_user.accounttype == "vendor" and current_user.identity_verified == 1) or (current_user.accounttype == "expert") or (current_user.accounttype == "admin") then
      self.reject_or_approve("approve", params[:id])
      self.redirection
    else
      redirect_to "/"
    end
  end

  # Helper functions
  def redirection
    if request.referer != nil then
      redirect_to request.referer
    else
      redirect_to '/vendor'
    end
  end

  def reject_or_approve(type, id)
    verb = "rejected"
    card_new_status = 0
    if type == "approve" then
      verb = "approved"
      card_new_status = 2
    end

    validation_queue = Validationqueue.where(:card_id => id)
    if validation_queue.length > 0 then
      card = Card.find(id)
      # Don't let users approve their own cards
      if card.owner_id.to_s != current_user._id then
        Cardnote.create(
          text: "Expert user #{verb} card",
          create_date: Time.new(),
          card_id: id.to_s
        )
        validation_queue.delete
        card.update_attributes(validation_status: card_new_status)
      end
    end
  end
end

app/views/cardverify/index.html.haml
.row
  .col-lg-6.col-md-6
    %h2{style:"color:#5f3d72"} Verify cards

.row.top-buffer
.col-lg-6.col-md-6
  %p Enter in the person's email to get a list of cards which they have requested a shopkeeper to verify.
  %p Only cards which are not in the transfer process can be verified. So the receiver needs to either take possession of the card in the system or reject it.
  %br
  = form_for :cardverify, url: cardverify_index_path, method: :get, role: "form", class: "form-horizontal" do |f|
    .col-lg-6.col-md-6
      %b Customer's Email Address
      %br
      = f.text_field :email, placeholder: "Enter email address here", size: 20, class: "form-control"
      %br
      = f.submit "Show list of cards", class: "btn btn-primary btn-purple"
      %br
      %br
  .col-lg-6.col-md-6
    -if @cardlist.length > 0
      -user = User.where(email: params[:cardverify][:email])[0]
      %p Here are a list of cards related to <b>#{user.class.human_attribute_name(user.name)} (#{params[:cardverify][:email]})</b>
      %table{width: "80%"}
        %thead
          %tr
            %th Card Name
            %th Actions
        %tbody

          -@cardlist.each do |i|
            %tr
              %td
                %a(href="/cards/detail/#{i[:_id]}") #{i[:cardname]}
              %td
                %a(href="/vendor/accept/#{i[:_id]}") Approve
                |
                %a(href="/vendor/reject/#{i[:_id]}") Reject

    -elsif @cardlist.length == 0 and params[:cardverify]
      -if params[:cardverify][:email]
        %table{width: "80%"}
          %tr
            %td
              %p There are no cards needing validation found for <b>#{params[:cardverify][:email]}</b>

app/views/cardverify/menu.html.haml
.row
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%h2{style:"color:#5f3d72"} #{I18n.t(current_user.accounttype.to_s).capitalize} tools

.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%p Welcome to the #{I18n.t(current_user.accounttype.to_s).capitalize} console.
		%p You may do the following tasks here:
.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%a.btn.btn-success.btn-purple(href="/cards/transfer/incoming") View any incoming transfers
		%br
		%br
		%a.btn.btn-success.btn-purple(href="/cards/new") Upload a card
		-if (current_user.accounttype == "vendor" and current_user.identity_verified == 1) or (current_user.accounttype == "expert")
			%a.btn.btn-success.btn-purple(href="/vendor/verify")Validate a card
		-else
			%br
			%br
			%a.btn.btn-success.disabled.btn-purple(href="#") Card Validation is only available to verified shopkeepers or users