config/routes.rb
Rails.application.routes.draw do
  # Custom pathnames
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register", :edit => "settings" }, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  # Default to cards index
  root to: "home#landing"

  #general pages
  get '/contact_careers' => 'home#contact_careers', as: :contact_careers
  get '/landing' => 'home#landing', as: :landing

  # Real Pages
  get '/cards/index' => 'cards#index', as: :cards_index
  get '/cards/edit/:id' => 'cards#edit', as: :cards_edit
  post '/cards/edit/:id' => 'cards#detail', as: :cards_edit_post_url
  get '/cards/new' => 'cards#new', as: :cards_new_url
  post '/cards/new' => 'cards#newform', as: :cards_post_url
  get '/cards/detail/:id' => 'cards#detail', as: :cards_detail_url
  post '/cards/detail/:id' => 'cards#detail', as: :cards_detail_post_url
  get '/cards/validate/:id' => 'cards#request_validation', as: :cards_validation_get_url
  get '/cards/cancelvalidation/:id' => 'cards#cancelvalidation', as: :cards_validation_cancel_url
  get '/cards/delete/:id' => 'cards#deletecard', as: :cards_delete_url
  get '/cards/undelete/:id' => 'cards#undeletecard', as: :cards_undelete_url
  get '/cards/graveyard' => 'cards#graveyard', as: :cards_graveyard_url

  # experts
  get '/experts' => 'home#showexperts', as: :experts_list_url

  # Vendor/Shopkeeper functionality
  get '/vendor' => 'cardverify#menu', as: :cardverify_menu
  get '/vendor/verify' => 'cardverify#index', as: :cardverify_index
  get '/vendor/reject/:id' => 'cardverify#rejectcard', as: :cardverify_reject
  get '/vendor/accept/:id' => 'cardverify#acceptcard', as: :cardverify_accept
  # Expert user functionality
  get '/expert' => 'cardverify#menu', as: :cardverify_menu_expert

  # Transfer functionality
  post '/cards/transfer' => 'transfer#outbound', as: :cardtransfer_outbound
  get '/cards/transfer/reject/:id' => 'transfer#rejecttransfer', as: :cardtransfer_reject
  get '/cards/transfer/accept/:id' => 'transfer#acceptransfer', as: :cardtransfer_accept
  get '/cards/transfer/incoming' => 'transfer#inbound', as: :cardtransfer_inbound

  # Admin page
  get '/admin' => 'adminpage#index', as: :adminpage_index
  get '/admin/generateinvite' => 'adminpage#generateinvite', as: :adminpage_generateinvite
  get '/admin/users' => 'adminpage#userlist', as: :adminpage_userlist
  get '/admin/transfers' => 'adminpage#transferlist', as: :adminpage_transferlist
  get '/admin/usercards/:id' => 'adminpage#usercards', as: :adminpage_usercards
  get '/admin/graveyard' => 'adminpage#graveyard', as: :adminpage_graveyard
  get '/admin/permadelete/:id' => 'cards#permadeletecard', as: :adminpage_permadelete

  # Fake pages
  get '/cards/transfer' => 'cards/transfer', as: :cards_transfer
  get '/cards/transferred' => 'cards/transferred', as: :cards_transferred
  get '/swhome' => 'home#index'
  match '/old/login' => 'login#login', :via => [:post]
  get '/old/sign_up' => 'login#logup', as: :logup
end

app/controllers/adminpage_controller.rb
require 'csv'

class AdminpageController < ApplicationController
  before_action :authenticate_user!
  # Index page
  def index
    if current_user.accounttype == "admin" then
      render :template => "adminpage/menu"
    else
      redirect_to "/"
    end
  end

  # Generate invite code
  def generateinvite
    if current_user.accounttype == "admin" then
      if params[:generateinvite] then
        if params[:generateinvite][:invitecode] == "yes" then
          @invitecode = Invitecode.create["code"]
        end
      end
    else
      redirect_to "/"
    end
  end

  # Show user list
  def userlist
    if current_user.accounttype == "admin" then
      @adminpage = User.all.paginate(:page => params[:page], :per_page => 20)
      @userlist = []
      @export_CSV = "name,email,accounttype,verified,cards,deleted\n"
      @adminpage.each {|user|
        verified = "no"
        if user[:identity_verified] == 1 then
          verified = "yes"
        end
        to_insert = {:id => user[:_id], :name => user[:name], :email => user[:email], :accounttype => user[:accounttype], :identity_verified => verified, :cards => Card.where(owner_id: user[:_id].to_s, :transfer_status => 0, :deleted_status => 0), :deleted_cards => Card.where(owner_id: user[:_id].to_s, :transfer_status => 0, :deleted_status => 1)}
        if params[:page]
          @page = params[:page]
        else
          @page = 1
        end
        @userlist << to_insert
        @export_CSV << "\"#{to_insert[:name]}\",\"#{to_insert[:email]}\",\"#{to_insert[:accounttype]}\",\"#{to_insert[:identity_verified]}\",\"#{to_insert[:cards].count}\",\"#{to_insert[:deleted_cards].count}\"\n"
      }
      respond_to do |format|
        format.html
        format.csv {send_data @export_CSV}
      end
    else
      redirect_to "/"
    end
  end

  # Show transfer list
  def transferlist
    if current_user.accounttype == "admin" then
      transferlist = Transfer.all
      @transferlist = []
      transferlist.each {|transfer|
        @transferlist << {:id => transfer[:_id], :asset_id => transfer[:asset_id], :asset_desc => Card.find(transfer[:asset_id]), :sender_email => transfer[:sender_email], :sender => User.where(:email => transfer[:sender_email]), :receiver_email => transfer[:receiver_email], :receiver => User.where(:email => transfer[:receiver_email])}
      }
    else
      redirect_to "/"
    end
  end

  # Def show user cards (basically a page which shows the type of cards)
  def usercards
    if current_user.accounttype == "admin" then
      @cards = Card.where(:owner_id => params[:id], :transfer_status => 0, :deleted_status => 0).order_by([:create_date, :desc]).paginate(:page => params[:page], :per_page => 6)
      @cardimages = []
      @cards.each{|card|
        cardimages_result = Cardimage.where(:card_id => card._id.to_s, :image_type => "front").order_by([:create_date, :desc]).limit(2)
        cardimages_result.each{|cardimage_result|
  				@cardimages << cardimage_result
  			}
        @cards_and_images = @cards.zip(@cardimages).map{|c,i| [c,i]}
      }
      @pagetitle = "User cards"
      @pagedescription = "List of all cards for this user"
    else
      redirect_to "/"
    end
  end

  def graveyard
    if current_user.accounttype == "admin" then
      @cards = Card.where(:transfer_status => 0, :deleted_status => 1).order_by([:create_date, :desc]).paginate(:page => params[:page], :per_page => 6)
      @cardimages = []
      @cards.each{|card|
        cardimages_result = Cardimage.where(:card_id => card._id.to_s, :image_type => "front").order_by([:create_date, :desc]).limit(2)
        cardimages_result.each{|cardimage_result|
  				@cardimages << cardimage_result
  			}
        @cards_and_images = @cards.zip(@cardimages).map{|c,i| [c,i]}
      }
      @pagetitle = "The Graveyard 👻💀"
      @pagedescription = "List of all deleted cards in the graveyard (deleted cards)"
      render "adminpage/usercards"
    else
      redirect_to "/"
    end
	end
end

app/views/adminpage/generateinvite.html.haml
.row
  .col-lg-6.col-md-6
    %h2{style:"color:#5f3d72"} Generate Invite code

.row.top-buffer
.col-lg-6.col-md-6
  %br
  = form_for :generateinvite, url: adminpage_generateinvite_path, method: :get, role: "form", class: "form-horizontal" do |f|
    .col-lg-6.col-md-6
      = f.hidden_field :invitecode, value: "yes"
      %br
      = f.submit "Generate Invite code", class: "btn btn-primary btn-purple"
      %br
      %br
  .col-lg-6.col-md-6
    -if @invitecode
      %p You can register with the following invite code: #{@invitecode}

app/views/adminpage/menu.html.haml
.row
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%h2{style:"color:#5f3d72"} Admin tools

.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%p Welcome to the admin console.
		%p You may do the following tasks here:
.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%a.btn.btn-success.btn-purple(href="/admin/transfers") View ALL card transfers
		%br
		%br
		%a.btn.btn-success.btn-purple(href="/cards/new") Upload a card
		%a.btn.btn-success.btn-purple(href="/vendor/verify")Validate a card
		%br
		%br
		%a.btn.btn-success.btn-purple(href="/admin/users")User Management
		%a.btn.btn-success.btn-purple(href="/admin/generateinvite")Generate Invite code
		%br
		%br
		%a.btn.btn-success.btn-purple(href="/admin/graveyard") All Deleted cards

app/views/adminpage/transferlist.html.haml
.row
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%h2{style:"color:#5f3d72"} Admin tools

.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%p List of active transfers in the system
.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		-if @transferlist.count > 0
			%ul
				-@transferlist.each do |transfer|
					%li Transfer of <a href="#" onclick="document.location.href='/cards/detail/#{transfer[:asset_id]}';">#{transfer[:asset_desc][:cardname]}</a> to #{transfer[:receiver_email]} from #{transfer[:sender][0][:name]} (#{transfer[:sender][0][:email]}). <a href="/cards/transfer/reject/#{transfer[:id]}">Reject?</a>
		-else
			%p No active transfers found

app/views/adminpage/usercards.html.haml
.row
	.col-lg-6.col-md-12
		%h2{style:"color:#5f3d72"} #{@pagetitle}

.row.top-buffer
	.col-lg-6.col-md-12
		%p #{@pagedescription}
	.col-lg-6.col-md-12
		= will_paginate @cards
.row.top-buffer
	-i = 0
	-@cards.each do |card|
		-i += 1
		.col-lg-3.col-md-4.col-xs-6.thumb
			%a.thumbnail{:href => "#", onclick: "document.location.href='/cards/detail/#{card.id}';"}
				-card_image_count = 0
				- @cardimages.each do |cardimage|
					-if card_image_count == 0 and cardimage.image_type == "front" and cardimage.card_id == card._id then
						%img.img-responsive{:src => "#{cardimage.photo.thumb.url}"}
						-card_image_count += 1
		-if i == 3
			.clearfix.visible-lg
			.clearfix.visible-xs
		-elsif i == 2
			.clearfix.visible-md
		-elsif i == 1
			.clearfix.visible-xs

app/views/adminpage/userlist.html.haml
.row
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%h2{style:"color:#5f3d72"} Admin tools

.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		%p List of all users on the system. You can download a copy by going <a href="#{adminpage_userlist_url}.csv?page=#{@page}">here</a>
.row.top-buffer
	.col-lg-4.col-md-4.col-lg-offset-4.col-md-offset-4
		-if @userlist.count > 0
			= will_paginate
			%ul
				-@userlist.each do |user|
					%li Name: #{user[:name]} Email: #{user[:email]} Verified: #{user[:identity_verified]} (Type: #{user[:accounttype]}) | Cards Owned: #{user[:cards].count} | Cards deleted: #{user[:deleted_cards].count} | <a href="/admin/usercards/#{user[:id]}">Show Cards</a>
		-else
			%p No users found