config/routes.rb
Rails.application.routes.draw do
  # Custom pathnames
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register", :edit => "settings" }, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  # Default to cards index
  root to: "home#landing"

  #general pages
  get '/contact_careers' => 'home#contact_careers', as: :contact_careers
  get '/landing' => 'home#landing', as: :landing

  # Real Pages
  get '/cards/index' => 'cards#index', as: :cards_index
  get '/cards/edit/:id' => 'cards#edit', as: :cards_edit
  post '/cards/edit/:id' => 'cards#detail', as: :cards_edit_post_url
  get '/cards/new' => 'cards#new', as: :cards_new_url
  post '/cards/new' => 'cards#newform', as: :cards_post_url
  get '/cards/detail/:id' => 'cards#detail', as: :cards_detail_url
  post '/cards/detail/:id' => 'cards#detail', as: :cards_detail_post_url
  get '/cards/validate/:id' => 'cards#request_validation', as: :cards_validation_get_url
  get '/cards/cancelvalidation/:id' => 'cards#cancelvalidation', as: :cards_validation_cancel_url
  get '/cards/delete/:id' => 'cards#deletecard', as: :cards_delete_url
  get '/cards/undelete/:id' => 'cards#undeletecard', as: :cards_undelete_url
  get '/cards/graveyard' => 'cards#graveyard', as: :cards_graveyard_url

  # experts
  get '/experts' => 'home#showexperts', as: :experts_list_url

  # Vendor/Shopkeeper functionality
  get '/vendor' => 'cardverify#menu', as: :cardverify_menu
  get '/vendor/verify' => 'cardverify#index', as: :cardverify_index
  get '/vendor/reject/:id' => 'cardverify#rejectcard', as: :cardverify_reject
  get '/vendor/accept/:id' => 'cardverify#acceptcard', as: :cardverify_accept
  # Expert user functionality
  get '/expert' => 'cardverify#menu', as: :cardverify_menu_expert

  # Transfer functionality
  post '/cards/transfer' => 'transfer#outbound', as: :cardtransfer_outbound
  get '/cards/transfer/reject/:id' => 'transfer#rejecttransfer', as: :cardtransfer_reject
  get '/cards/transfer/accept/:id' => 'transfer#acceptransfer', as: :cardtransfer_accept
  get '/cards/transfer/incoming' => 'transfer#inbound', as: :cardtransfer_inbound

  # Admin page
  get '/admin' => 'adminpage#index', as: :adminpage_index
  get '/admin/generateinvite' => 'adminpage#generateinvite', as: :adminpage_generateinvite
  get '/admin/users' => 'adminpage#userlist', as: :adminpage_userlist
  get '/admin/transfers' => 'adminpage#transferlist', as: :adminpage_transferlist
  get '/admin/usercards/:id' => 'adminpage#usercards', as: :adminpage_usercards
  get '/admin/graveyard' => 'adminpage#graveyard', as: :adminpage_graveyard
  get '/admin/permadelete/:id' => 'cards#permadeletecard', as: :adminpage_permadelete

  # Fake pages
  get '/cards/transfer' => 'cards/transfer', as: :cards_transfer
  get '/cards/transferred' => 'cards/transferred', as: :cards_transferred
  get '/swhome' => 'home#index'
  match '/old/login' => 'login#login', :via => [:post]
  get '/old/sign_up' => 'login#logup', as: :logup
end

app/models/card.rb
class Card
  include Mongoid::Document
  store_in collection: "cards"
  #attr_accessible :image

  field :description, type: String
  field :cardname, type: String
  field :cardgame, type: String
  field :cardcollection, type: String
  field :create_date, type: DateTime, default: ->{ Time.new }
  field :update_date, type: DateTime, default: ->{ Time.new }
  field :card_condition, type: String, default: 'mint' # Should be either 'mint', 'slightly worn', 'damaged'
  field :validation_status, type: Integer, default: 0 # 0 = Unverified, 1 = Pending, 2 = Validated
  field :transfer_status, type: Integer, default: 0 # 0 = not being transferred, 1 = Pending (lets filter by this)
  field :owner_id, type: String

  field :unique_identifier, type: String, default: -> {s = "VA-" ; 7.times{|i| s+='ABCDEFGHIJKLMNOPQRSTUVWXYZ'[rand(26), 1]} ; s = s + "-#{(Card.count + 1).to_s}"; s}

  # Deleted
  field :deleted_status, type: Integer, default: 0 # Not deleted, 1 = deleted

  # Text
  field :searchable_name, type: String

  # Types of fields
  # Array
  # BigDecimal
  # Boolean
  # Date
  # DateTime
  # Float
  # Hash
  # Integer
  # BSON::ObjectId
  # BSON::Binary
  # Range
  # Regexp
  # String
  # Symbol
  # Time
  # TimeWithZone

  mount_uploader :photo, CarduploaderUploader
  #don't delete yet
  # def self.find_with_pagination(params = {}, filters = {})
  #   WillPaginate::Collection.create(params[:page].to_i < 1 ? 1 : params[:page], per_page_for_page(params[:page])) do |pager|
  #     result = Card.all.limit(pager.per_page).offset(offset_for_page(params[:page])).where(filters)
  #     pager.replace result
  #     unless pager.total_entries
  #       # the pager didn't manage to guess the total count, do it manually
  #       pager.total_entries = self.count
  #     end
  #   end
  # end

  # def self.offset_for_page(page_number)
  #   page_number.to_i > 1 ? ((page_number.to_i - 2) * 8 + 7) : 0
  # end

  # def self.per_page_for_page(page_number)
  #   page_number.to_i > 1 ? 8 : 7
  # end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	include CardsHelper
	before_action :authenticate_user!
	before_action :set_card_form, only: [:detail]
	before_action :set_find_owner_form, only: [:detail]
	layout 'application'

	def index
		flash[:info] = nil # Remove any info stuff
		@listincoming = Transfer.where(receiver_email: current_user.email).count # Check i
		@owner_cards = Card.where(:owner_id => current_user.id.to_s, :transfer_status => 0, :deleted_status => 0).order_by([:create_date, :desc])
		@cards = params[:search_text].present? ? @owner_cards.where(searchable_name:  /#{Regexp.escape(params[:search_text].downcase.to_s)}/).paginate(:page => params[:page], :per_page => 7) : @owner_cards.paginate(:page => params[:page], :per_page => 7)
		# raise params[:search_text].inspect
		# .order_by([:updated_at, :asc])
		# If no cards, show new card url
		# If no cards and shopkeeper, show vendor url
		#if current_user.accounttype == "vendor" and @cards.length == 0 then
		#	redirect_to "/vendor"
		#end
		@cardimages = []
		@cards.each{|card|
			puts card.photo.url
			puts card.photo.thumb.url

			cardimages_result = Cardimage.where(:card_id => card._id.to_s, :image_type => "front").order_by([:create_date, :desc]).limit(2)
			cardimages_result.each{|cardimage_result|
				@cardimages << cardimage_result
			}
		}
		@cards_and_images = @cards.zip(@cardimages).map{|c,i| [c,i]}
		# @cards_search = Cardnote.where({cardname: "#{params[:search_text]}"})
		respond_to do |format|
		  format.html
		  format.js
		end
	end

	def graveyard
		@cards = Card.where(:owner_id => current_user.id.to_s, :transfer_status => 0, :deleted_status => 1).order_by([:create_date, :desc])
	end

	def edit
		@card = Card.where(:id => params[:id].to_s)[0]
	end

	# POST /cards/new
	def newform
		flash[:info] = {}
		flash[:info][:cardname] = params[:cards]["name"]
		flash[:info][:cardgame] = params[:cards]["game"]
		flash[:info][:cardcollection] = params[:cards]["collection"]
		flash[:info][:card_condition] = params[:cards]["card_condition"].to_s
		flash[:info][:card_condition_select] = params[:cards]["card_condition_select"].to_s
		if params[:cards]["name"].to_s == "" then
			cardname = "(not set)"
		else
			cardname = params[:cards]["name"].to_s
		end
		if params[:cards]["card_condition_select"].to_s == "Other" then
			if params[:cards]["card_condition"].to_s == "" then
				card_condition = "(not set)"
			else
				card_condition = params[:cards]["card_condition"].to_s
			end
		else
			card_condition = params[:cards]["card_condition_select"]
			flash[:info][:card_condition] = card_condition
		end
		if card_condition != "" and params[:cards]["userid"] != "" and cardname != "" and params[:cards]["game"] != "" and params[:cards]["collection"] != "" then
			# Front image is required
			if params[:cards]["front_image"] then
				card_created = Card.create(
					cardname: cardname,
					cardgame: params[:cards]["game"].to_s,
					searchable_name: cardname.downcase.to_s,
					cardcollection: params[:cards]["collection"].to_s,
					card_condition: card_condition.to_s,
					create_date: Time.new(),
					update_date: Time.new(),
					owner_id: params[:cards]["userid"].to_s
				)
				if params[:cards]["card_condition_select"].to_s == "Other" then
					# Store Cardcondition so we have a list of what people are entering if other is selected
					Cardcondition.create(
						condition: card_condition.to_s.downcase
					)
				end
				Cardnote.create(
					text: "Card initial upload complete",
					create_date: Time.new(),
					card_id: card_created._id.to_s
				)
				# Create Front image
				Cardimage.create(
					create_date: Time.new(),
					photo: params[:cards]["front_image"],
					image_type: "front",
					image_note: "Front image uploaded",
					card_id: card_created._id.to_s
				)
				# Create back image if exists
				if params[:cards]["back_image"] then
					Cardimage.create(
						create_date: Time.new(),
						photo: params[:cards]["back_image"],
						image_type: "back",
						image_note: "Back image uploaded",
						card_id: card_created._id.to_s
					)
				end
				redirect_to :cards_index
			else
				puts "Need a picture"
				flash[:error] = "A card must require a front image"
				redirect_to request.original_fullpath
			end
		else
			puts "Invalid parameters"
			flash[:error] = "The form must be completed before continuing"
			redirect_to request.original_fullpath
		end
	end
	# GET /cards/new
	def new
		if flash[:info] == nil then
			flash[:info] = {}
			flash[:info][:cardname] = ""
			flash[:info][:cardgame] = "Magic: The Gathering"
			flash[:info][:cardcollection] = "Default collection"
			flash[:info][:card_condition] = ""
		end
		puts flash.inspect
		# Populate dropdowns
		@cardcollection = []
		@gamelist = []
		Cardgame.each{|game| @gamelist << game.gamename }
		Cardcollection.each{|coll| @cardcollection << coll.collectionname}
		render :template => "cards/new"
	end

	def detail
		puts "ID: #{params[:id]}"
		cards = Card.where(:id => params[:id].to_s)
		if cards.length == 1 then
			@card = cards[0]
			@cardnote = Cardnote.where(:card_id => @card._id.to_s).order_by([:create_date, :desc]).limit(5)
			cardimages_1 =  Cardimage.where(:card_id => @card._id.to_s, :image_type => 'front').order_by([:image_type, :desc],[:create_date, :desc]).limit(1)
			cardimages_2 =  Cardimage.where(:card_id => @card._id.to_s, :image_type => 'back').order_by([:image_type, :desc],[:create_date, :desc]).limit(1)
			@cardimages = []
			cardimages_1.each{|card_1|
				@cardimages << card_1
			}
			cardimages_2.each{|card_2|
				@cardimages << card_2
			}
			if @card[:unique_identifier] == nil then
				if @card[:unique_identifier] == "" then
					rs = "VA-"
					7.times{|i| rs+='ABCDEFGHIJKLMNOPQRSTUVWXYZ'[rand(26), 1]}
					rs = rs + "-#{(Card.count + 1).to_s}"
					@card.update_attributes(:unique_identifier => rs)
					@card.save
					@card[:unique_identifier] = rs
				else
					@card.update_attributes(:unique_identifier => @card[:unique_identifier])
				end
			else
				@card.update_attributes(:unique_identifier => @card[:unique_identifier])
			end
			# Check if owner matches the database
			if (@card.owner_id == current_user._id.to_s) or ((current_user.accounttype == "vendor" and current_user.identity_verified == 1) or (current_user.accounttype == "expert") or (current_user.accounttype == "admin")) then
				@method = env['REQUEST_METHOD']
				if current_user.timezone == '' or current_user.timezone == nil then
					@timezone = current_user.timezone
				else
					@timezone = current_user.timezone
				end
				if env['REQUEST_METHOD'] == "GET" then
					# get Owner info
					if @card.owner_id.to_s != current_user._id.to_s then
						# if the owner doesnt match
						@card_owner_info = User.find(@card.owner_id)
					else
						# If the owner matches
						@card_owner_info = current_user
					end
					render :template => "cards/detail"
				else
					puts "POST detected"
					if params[:cards].present?
						puts "Params: card_id=#{params[:id]}, notes_text=#{params[:cards]['notes_text']}"
						puts "Full cards params: #{params[:cards].inspect}"
						notes_text = ''
						if params[:cards]['image_only_upload'] == 'true' then
							notes_text = 'Replace card image'
						end
						if params[:cards]['cardname'] or params[:cards]['card_condition'] then
							puts "Lets update card id=#{@card._id}"
							update_card = Card.find(@card._id)
							# Check if the entry is different
							if params[:cards]['cardname'].to_s != update_card['cardname'] then
								if params[:cards]['cardname'].to_s.length > 0 then
									notes_text = "Change card name from \"#{update_card['cardname']}\" to \"#{params[:cards]['cardname'].to_s}\""
								end
							end
							if params[:cards]["card_condition_select"] != "Other"  then
								if update_card['card_condition'].to_s != params[:cards]["card_condition"].to_s then
									# use the typed condition if the name is different
									card_condition = params[:cards]["card_condition"].to_s
								else
									# If the name is the same then use the selectbox
									card_condition = params[:cards]["card_condition_select"].to_s
								end
							else
								card_condition = params[:cards]["card_condition"].to_s
							end
							if card_condition.downcase != update_card['card_condition'].to_s.downcase then
								if card_condition.to_s.length > 0 then
									if notes_text.to_s.length > 0
										notes_text = "#{notes_text}, and c"
									else
										notes_text = "C"
									end
									notes_text = "#{notes_text}hange card condition from \"#{update_card['card_condition'].to_s}\" to \"#{card_condition.to_s}\""
								end
							end
							if params[:cards]['notes_text'] then
								if params[:cards]['notes_text'].to_s.length > 1 and params[:cards]['notes_text'].to_s.length <= 500 then
									if notes_text == '' then
										notes_text = params[:cards]['notes_text'].to_s
									else
										notes_text = "#{notes_text}. User comment: \"#{params[:cards]['notes_text']}\""
									end
								end
							end
						end
						if notes_text != '' then
							# Create a card note
							Cardnote.create(
								text: notes_text.to_s,
								create_date: Time.new(),
								card_id: params[:id].to_s
							)
							# Check images
							if params[:cards]['front_image'] != nil then
								Cardimage.create(
									create_date: Time.new(),
									photo: params[:cards]['front_image'],
									image_type: "front",
									image_note: "front image uploaded",
									card_id: params[:id].to_s
								)
							end # END: Check front image
							if params[:cards]['back_image'] != nil then
							# if a new back image is specified
								Cardimage.create(
									create_date: Time.new(),
									photo: params[:cards]["back_image"],
									image_type: "back",
									image_note: "Back image uploaded",
									card_id: params[:id].to_s
								)
							end # END: Check back image
							if params[:cards]['cardname'] then

app/helpers/cards_helper.rb
module CardsHelper
  def remove_card(id)
    begin
      card_to_permadelete = Card.find(id)
      if card_to_permadelete then
        Cardimage.where(card_id: id.to_s).each{|cardimage|
					cardimage.destroy
				}
				# Now remove the notes
				Cardnote.where(card_id: id.to_s).each{|cardnote|
					cardnote.destroy
				}
				# Delete the card
				card_to_permadelete.destroy

        # All done!
        true
      else
        false
      end
    rescue
      false
    end
  end

  class ValidateCardCondition
    def self.valid_condition(condition)
      if condition == "mint" or condition == "slightly worn" or condition == "worn" or condition == "damaged" then
        true
      else
        false
      end
    end

    def self.change_condition(before, after)
      if before == "mint" then
        # mint can go to any status
        true
      elsif before == "slightly worn" then
        # can go anywhere but mint
        if after != "mint" then
          true
        else
          false
        end
      elsif before == "worn" then
        # can only be set to damaged
        if after == "damaged" then
          true
        else
          false
        end
      else
        # damaged can't be changed
        false
      end
    end
  end
end

app/views/cards/_add_picture_form.html.haml
-if flash
  %ul
    -flash.each do |key, value|
      -if key == "error"
        %li #{key.capitalize}: #{value}
= form_for :cards, url: cards_detail_post_url_path, method: :post, role: "form", class: "form-horizontal add_picture_form" do |f|
  = f.hidden_field :image_only_upload, value: "true"
  %b Front of card (Optional: if already have back image):
  %br
  = f.file_field "front_image", class: "btn btn-primary btn-purple btn-upload"
  .top-buffer
  %b Back of card (Optional: if already have front image):
  %br
  = f.file_field "back_image", class: "btn btn-primary btn-purple btn-upload"
  %br
  .top-buffer
  = f.submit "Submit", class: "btn btn-primary btn-purple"

app/views/cards/_addnote.html.haml
-if flash
  %ul
    -flash.each do |key, value|
      -if key == "error"
        %li #{key.capitalize}: #{value}
= form_for :cards, url: cards_detail_post_url_path, method: :post, role: "form", class: "form-horizontal" do |f|
  .row
    .col-lg-4.col-sm-4
      %b Front of image (Required*):
      = f.file_field "front_image", class: "btn btn-primary btn-purple"
    .col-lg-4.col-sm-4
      %b Back of image (Optional*):
      = f.file_field "back_image", class: "btn btn-primary btn-purple"
  .top-buffer
  = f.submit "Submit", class: "btn btn-primary btn-purple"

app/views/cards/_form.html.haml
.row
	.col-lg-6.col-md-6
		%span{style: "color: #5f3d72"}
			.h1 Edit Card Info
		-if flash
			%ul
				-flash.each do |key, value|
					-if key == "error"
						%li #{key.capitalize}: #{value}

.row.top-buffer
	= form_for :cards, url: cards_edit_post_url_url, method: :post, role: "form", class: "form-horizontal" do |f|
		.col-lg-6.col-md-6
			%b Card name:
			%br
			= f.text_field :cardname, placeholder: "Name of Card", class: "form-control", value: @card.cardname.to_s
			%br
			// = f.text_field :cardgame, placeholder: "Game", class: "form-control"
			// %br
			// = f.text_field :cardcollection, placeholder: "Set", class: "form-control"
			// %br
			%br
			-if @card.card_condition != "damaged"
				%br
				%b Card Condition (based on the <a href="https://help.tcgplayer.com/hc/en-us/articles/201432037-Magic-the-Gathering-Card-Conditions" target="cardconditon">TCG Guidelines</a>)
				&nbsp;
				-default_condition = "Other"
				-if ["Other", "Near Mint", "Lightly Played", "Moderately Played", "Heavily Played", "Damaged"].join.to_s.include? @card.card_condition.to_s
					-default_condition = @card.card_condition
				= f.select :card_condition_select, ["Other", "Near Mint", "Lightly Played", "Moderately Played", "Heavily Played", "Damaged"], class: "form-control", selected: default_condition
				%br
				%br
				%b Card condition not listed or something else?:
				%br
				= f.text_field :card_condition, placeholder: "Type in the new card condition here", class: "form-control", value: @card.card_condition.to_s
				%br
				%br
			-else
				%b As your card is already in the damaged state, you can't change the condition for this
				%br
				%br
			%b Additional Notes:
			%br
			= f.text_field :notes_text, placeholder: "Enter a comment", maxlength: 500, class: "form-control"
			%br
			.top-buffer
			= f.submit "Add comment to Card", class: "btn btn-primary btn-purple"
			%br
			%br
			%br
			%br

app/views/cards/detail.html.haml
-if flash
  .row
    %ul
      -flash.each do |key, value|
        -if key == "error"
          %li #{key.capitalize}: #{value}

.row.top-buffer-2
  .col-lg-12.col-md-12.col-sm-12
    -if @card.owner_id == current_user._id.to_s and @card.deleted_status != 1
      -if @card.transfer_status != 1 and (@card.validation_status == 0 or @card.validation_status == 2)
        / .btn-group
        .col-lg-3.col-md-3.col-sm-6
          %button#pop_up_btn.btn.btn-primary.btn-purple.btn-block{ rel: "popover", data: {content: "#{@card_form}", toggle: "popover", placement: "bottom", title: "Add Pictures"} }
            %i.glyphicon.glyphicon-camera
            &nbsp;
            #{I18n.t('addpicturesbutton')}
          &nbsp;
        .col-lg-3.col-md-3.col-sm-6
          %button#pop_up_btn.btn.btn-primary.btn-purple.btn-block{ rel: "popover", data: {content: "#{@find_owner_form}", toggle: "popover", placement: "bottom", title: "Future Owner"} }
            %i.glyphicon.glyphicon-send
            &nbsp;
            #{I18n.t('transferownerbutton')}
          &nbsp;
        .col-lg-3.col-md-3.col-sm-6
          -if (@card.validation_status == 0 or @card.validation_status == 2) and (@card.transfer_status != 1)
            =link_to cards_edit_path(@card), role: "button",  class: "btn btn-primary btn-purple btn-block" do
              %i.glyphicon.glyphicon-pencil
              &nbsp;
              #{I18n.t('editnotesbutton')}
            &nbsp;
        .col-lg-3.col-md-3.col-sm-6
          -if @card.owner_id == current_user._id.to_s and (@card.validation_status == 0 or @card.validation_status == 2) and (@card.transfer_status != 1) and (@card.deleted_status == 0)
            =link_to cards_delete_url_path(@card), data: { confirm: "Really delete this card?" }, class: "btn btn-primary btn-red btn-block", role: "button" do
              %i.glyphicon.glyphicon-fire
              &nbsp;
              #{I18n.t('deletebutton')}
          -elsif current_user.accounttype == "admin" and (@card.deleted_status == 1)
            =link_to I18n.t('undelete'), cards_undelete_url_path(@card), data: { confirm: "Please make sure you have the consent of the owning user before doing so. Really ressurrect this card from the graveyard?" }, class: "btn btn-primary btn-purple"
            =link_go I18n.t('permadelete'), adminpage_permadelete(@card), data: { confirm: "This card will permanently remove this card FOREVER" }, class: "btn btn-primary btn-purple"
    -elsif ((current_user.accounttype == "vendor" and current_user.identity_verified == 1) or (current_user.accounttype == "expert") or (current_user.accounttype == "admin")) and @card.owner_id != current_user._id.to_s and @card.validation_status == 1
      =link_to "#{I18n.t('approvebutton')}", "/vendor/accept/#{@card.id}", class: 'btn btn-primary btn-purple'
      =link_to "#{I18n.t('rejectbutton')}", "/vendor/reject/#{@card.id}", class: 'btn btn-primary btn-purple'
    -elsif current_user.accounttype == "admin" and (@card.deleted_status == 1)
      =link_to I18n.t('undelete'), cards_undelete_url_path(@card), data: { confirm: "Please make sure you have the consent of the owning user before doing so. Really ressurrect this card from the graveyard?" }, class: "btn btn-primary btn-purple"
      &nbsp;
      =link_to I18n.t('permadelete'), adminpage_permadelete_path(@card), data: { confirm: "This card will permanently remove this card FOREVER" }, class: "btn btn-primary btn-purple"

.row.top-buffer
  -if @cardimages.length == 0 then
    #{I18n.t('noimagesfound')}
  -else
    -size = @cardimages.size
    -imgcounter = 0
    -@cardimages.each do |cardimage|
      -imgcounter += 1
      -if size == 1
        .col-lg-8.col-md-4.col-sm-8
          / %h4 #{cardimage.image_type.capitalize} of card
          %img.img-responsive{:src => "#{cardimage.photo.thumb.url}", alt: "#{cardimage.image_type}"}
          %br
          %a{:href => "#{cardimage.photo.url}", :target => "newpicture1"} #{I18n.t('showoriginalcard')}
          %br
      -else
        .col-lg-4.col-md-4.col-sm-4
          / %h4 #{cardimage.image_type.capitalize} of card
          %img.img-responsive{:src => "#{cardimage.photo.thumb.url}", alt: "#{cardimage.image_type}"}
          %a{:href => "#{cardimage.photo.url}", :target => "newpicture#{imgcounter.to_s}"} #{I18n.t('showoriginalcard')}
          %br
  .col-lg-4.col-md-4.col-sm-4
    .card-info-table
      %table
        %tbody
          %tr
            %th #{I18n.t('cardidentifier')}
            %td #{@card.unique_identifier}
          %tr
            %th #{I18n.t('cardname')}:
            %td #{@card.cardname}
          %tr
            %th #{I18n.t('cardgame')}:
            %td #{@card.cardgame}
          %tr
            %th #{I18n.t('cardcondition')}:
            %td #{@card.card_condition.to_s}
          %tr
            %th #{I18n.t('cardstatus')}:
            -case @card.validation_status
              -when 0
                -if @card.transfer_status != 1 and (@card.owner_id.to_s == current_user._id.to_s) and (@card.deleted_status == 0)
                  %td #{I18n.t('statusunchecked')} (<a href="#{cards_validation_get_url_path(@card)}" data-confirm="This process will PREVENT you from making further changes to the card until it is validated. Are you sure?">Ask for Expert Check</a>)
                -else
                  %td #{I18n.t('statusunchecked')}
              -when 1
                -if @card.transfer_status != 1 and (@card.owner_id.to_s == current_user._id.to_s) and (@card.deleted_status == 0)
                  %td #{I18n.t('statuspending')} (<a href="#{cards_validation_cancel_url_path(@card)}">Cancel Expert Validation</a>)
                -else
                  %td #{I18n.t('statuspending')}
              -when 2
                %td #{I18n.t('statusverified')}
              -else
                %td #{I18n.t('statusunknown')}
          %tr
            %th #{I18n.t('cardcreatedate')}:
            %td #{Time.at(@card.create_date).in_time_zone(@timezone).strftime "%e %b %Y %H:%M %z"}
          %tr
            %th #{I18n.t('cardowner')}:
            %td #{@card_owner_info.name}

=render "listnote"
%br
%br

app/views/cards/edit.html.haml
=render "form"

app/views/cards/transfer.html.haml
%br
%br
.row
	.col-sm-6
		.table-responsive
			%table
				%tbody
					%tr
						%th= image_tag('front_2.jpg', width: "200")
						%th= image_tag('back_2.jpg', width: "200")
						%th{colspan:'2'}
	.col-sm-6
		.h2 Swell of Growth
		.h3 Magic the Gathering
		<b>Uploaded:</b> 2015-01-23
		%br
		<b>Owner:</b> Sophie
		%br
		%br
		%th= image_tag('verified.png')
.row
	.col-sm-6
		.table-responsive
			%table
				%tbody
					%tr
						%th= image_tag('front_1.jpg', width: "50")
						%th= image_tag('back_1.jpg', width: "50")
.row
	%h3 future Owner
	%input.form-control{:placeholder => "Email", style: "width: 150px;", :type => "email"}
	%br
	%input.form-control{:placeholder => "Name", style: "width: 150px;", :type => "name"}

.row.validate_btn
	=link_to "Transfer", cards_transferred_path, class: "btn btn-primary btn-landing btn_up"

%br
%br
%br
%br